# Generated by Django 2.0.2 on 2018-08-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blog_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Post',
            new_name='Job_Post',
        ),
    ]
