# Generated by Django 2.0.2 on 2018-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180819_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
